[[main]]
none = "none"

[[main]]
name = "Linux"
pageRef = "linux"
identifier = "0urHbhnS4x"
weight = 1

[[main]]
name = "Docker"
pageRef = "docker"
identifier = "CMRcLrVWSH"
weight = 2

[[footer]]
none = "none"
